name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ]
        env:
          - environment-dev.yml

    steps:
    - uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: ${{ matrix.env }}
        miniforge-version: latest
        miniforge-variant: Mambaforge
        use-mamba: true

    - name: Package Test
      run: |
        conda activate rasterexplorer-dev
        pytest